export type profileProps = {
    id: string,
    nama: string,
    nip: string,
    tempat_lahir: string,
    ttl: string,
    file: string,
    metode_absen: number,
    gelar_depan: string,
    gelar_belakang: string,
    email: string,
    nm_unit_kerja: string,
    instansi_id: string,
    instansi: string,
    nm_jabatan: string,
    agama_uraian: string,
    status_keluarga_uraian: string,
    jns_golongan_id: number,
    tmt_gol: string,
    gol_uraian: string,
    strata_ijazah_id: number,
    nm_sekolah: string,
    pendidikan_ahir_uraian: string,
    pendidikan_formal_thn_lulus: number
}